create database QLHS
USE [QLHS]
GO

/****** Object:  Table [dbo].[BANGDIEM]    Script Date: 5/11/2018 6:59:10 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BANGDIEM](
	[MANH] [int] NOT NULL,
	[MALOP] [int] NOT NULL,
	[MAHK] [int] NOT NULL,
	[MAMH] [int] NOT NULL,
	[MAHS] [int] NOT NULL,
	[DIEMMIENG] [float] NULL,
	[DIEM15PL1] [float] NULL,
	[DIEM15PL2] [float] NULL,
	[DIEM15PL3] [float] NULL,
	[DIEM1TL1] [float] NULL,
	[DIEM1TL2] [float] NULL,
	[DIEM1TL3] [float] NULL,
	[DIEMHOCKY] [float] NULL,
	[DTBMON] [float] NULL,
	[HESOMON] [int] NULL,
 CONSTRAINT [PK_BANGDIEM_1] PRIMARY KEY CLUSTERED 
(
	[MANH] ASC,
	[MALOP] ASC,
	[MAHK] ASC,
	[MAMH] ASC,
	[MAHS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO




/****** Object:  Table [dbo].[BAOCAOHK]    Script Date: 5/11/2018 6:59:24 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BAOCAOHK](
	[MANH] [int] NOT NULL,
	[MAHK] [int] NOT NULL,
	[MALOP] [int] NOT NULL,
	[SLDAT] [float] NULL,
	[TILEHK] [float] NULL,
 CONSTRAINT [PK_BAOCAOHK] PRIMARY KEY CLUSTERED 
(
	[MANH] ASC,
	[MAHK] ASC,
	[MALOP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


/****** Object:  Table [dbo].[BAOCAOMON]    Script Date: 5/11/2018 6:59:34 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BAOCAOMON](
	[MAMH] [int] NOT NULL,
	[MANH] [int] NOT NULL,
	[MALOP] [int] NOT NULL,
	[MAHK] [int] NOT NULL,
	[SLDAT] [float] NULL,
	[TILE] [float] NULL,
 CONSTRAINT [PK_BAOCAOMON] PRIMARY KEY CLUSTERED 
(
	[MAMH] ASC,
	[MANH] ASC,
	[MALOP] ASC,
	[MAHK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO







/****** Object:  Table [dbo].[CHITIETLOP]    Script Date: 5/11/2018 6:59:42 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CHITIETLOP](
	[MAHS] [int] NOT NULL,
	[MALOP] [int] NOT NULL,
	[MANH] [int] NOT NULL,
 CONSTRAINT [PK_CHITIETLOP] PRIMARY KEY CLUSTERED 
(
	[MAHS] ASC,
	[MALOP] ASC,
	[MANH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO






/****** Object:  Table [dbo].[HOCKY]    Script Date: 5/11/2018 6:59:53 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[HOCKY](
	[MAHK] [int] NOT NULL,
	[TENHK] [varchar](10) NULL,
	[MANH] [int] NOT NULL,
 CONSTRAINT [PK_HOCKY_1] PRIMARY KEY CLUSTERED 
(
	[MAHK] ASC,
	[MANH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO










/****** Object:  Table [dbo].[HOCSINH]    Script Date: 5/11/2018 7:00:04 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[HOCSINH](
	[MAHS] [int] IDENTITY(1,1) NOT NULL,
	[HOTEN] [varchar](40) NOT NULL,
	[DIACHI] [varchar](40) NOT NULL,
	[NGAYSINH] [datetime] NOT NULL,
	[GIOITINH] [varchar](40) NOT NULL,
	[TONGIAO] [varchar](40) NOT NULL,
	[DANTOC] [varchar](40) NOT NULL,
	[HOTENCHA] [varchar](40) NULL,
	[NGHENGHIEPCHA] [varchar](40) NULL,
	[HOTENME] [varchar](40) NULL,
	[NGHENGHIEPME] [varchar](40) NULL,
	
 CONSTRAINT [PK_HOCSINH] PRIMARY KEY CLUSTERED 
(
	[MAHS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO






/****** Object:  Table [dbo].[KHOILOP]    Script Date: 5/11/2018 7:00:16 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[KHOILOP](
	[MAKHOI] [int] IDENTITY(1,1) NOT NULL,
	[TENKHOI] [nchar](10) NULL,
 CONSTRAINT [PK_KHOILOP] PRIMARY KEY CLUSTERED 
(
	[MAKHOI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO





/****** Object:  Table [dbo].[LOPHOC]    Script Date: 5/11/2018 7:00:26 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[LOPHOC](
	[MALOP] [int] NOT NULL,
	[TENLOP] [varchar](20) NULL,
	[MAKHOI] [int] NULL,
	[SISO] [int] NULL,
	[TENGVCN] [varchar](50) NULL,
	[MANH] [int] NULL,
 CONSTRAINT [PK_LOPHOC] PRIMARY KEY CLUSTERED 
(
	[MALOP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO








/****** Object:  Table [dbo].[MONHOC]    Script Date: 5/11/2018 7:00:51 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MONHOC](
	[MAMH] [int] NOT NULL,
	[TENMH] [nvarchar](10) NULL,
	[HESO] [int] NULL,
 CONSTRAINT [PK_MONHOC] PRIMARY KEY CLUSTERED 
(
	[MAMH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO





/****** Object:  Table [dbo].[NAMHOC]    Script Date: 5/11/2018 7:01:00 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[NAMHOC](
	[MANH] [nchar](10) NOT NULL,
	[TENNH] [nchar](10) NULL,
 CONSTRAINT [PK_NAMHOC] PRIMARY KEY CLUSTERED 
(
	[MANH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO






/****** Object:  Table [dbo].[NGUOIDUNG]    Script Date: 5/11/2018 7:01:10 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[NGUOIDUNG](
	[TENDN] [nvarchar](50) NOT NULL,
	[PASS] [char](30) NULL,
	[TENNGUOIDUNG] [char](100) NULL,
	[LEVEL] [int] NULL,
 CONSTRAINT [PK_NGUOIDUNG] PRIMARY KEY CLUSTERED 
(
	[TENDN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO






/****** Object:  Table [dbo].[QUYDINH]    Script Date: 5/11/2018 7:01:20 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[QUYDINH](
	[TUOIMAX] [int] NULL,
	[TUOIMIN] [int] NULL,
	[SISO] [int] NULL,
	[DIEMDAT] [int] NULL,
	[DIEMMAX] [int] NULL,
	[DIEMMIN] [int] NULL,
	[SLMON] [int] NULL,
	[LOP10] [int] NULL,
	[LOP11] [int] NULL,
	[LOP12] [int] NULL
) ON [PRIMARY]

GO






/****** Object:  Table [dbo].[TONGKETCANAM]    Script Date: 5/11/2018 7:01:27 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TONGKETCANAM](
	[MAHS] [int] NOT NULL,
	[MALOP] [int] NOT NULL,
	[MANH] [int] NOT NULL,
	[TBCANAM] [float] NULL,
	[HANHKIEM] [nchar](10) NULL,
 CONSTRAINT [PK_TONGKETCANAM] PRIMARY KEY CLUSTERED 
(
	[MAHS] ASC,
	[MALOP] ASC,
	[MANH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO






/****** Object:  Table [dbo].[TONGKETHOCKY]    Script Date: 5/11/2018 7:01:45 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TONGKETHOCKY](
	[MAHS] [int] NOT NULL,
	[MALOP] [int] NOT NULL,
	[MAHK] [int] NOT NULL,
	[MANH] [int] NOT NULL,
	[TBHK] [nchar](10) NULL,
	[HANHKIEM] [nchar](10) NULL,
 CONSTRAINT [PK_TONGKETHOCKY] PRIMARY KEY CLUSTERED 
(
	[MAHS] ASC,
	[MALOP] ASC,
	[MAHK] ASC,
	[MANH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO





/****** Object:  Table [dbo].[TONGKETMON]    Script Date: 5/11/2018 7:01:52 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TONGKETMON](
	[MATKMON] [int] NOT NULL,
	[MAMH] [int] NULL,
	[MAHK] [int] NULL,
	[MALOP] [int] NULL,
	[SLDAT] [float] NULL,
	[TILEMON] [float] NULL,
 CONSTRAINT [PK_TONGKETMON] PRIMARY KEY CLUSTERED 
(
	[MATKMON] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO











